### PR TITLE
Advanced Lists and Editing

### PR DESCRIPTION
**Pull request by JoshTheDerf**
This is an extension of #1, but changes quite a few things:
- Bump version to 0.2.0 as mentioned in #2.
- Now requires tabs permission.
- Allows for separate list creation, default lists (kinda, still working on this a bit.), and edit-locked lists.
- Lists can be enabled, disabled, repositioned, renamed, and tied to specific pages and sites. (Still allows wildcards)
- Rules can be edited and repositioned in the same way as before.
- The matchProtocol option has been removed and now uses the matching method described in #2.
- `utils/url.js` has been removed and is no longer needed.
- Removed the html5shiv rule, since that can now be added in a user list.
- Added youtube-related rules, and loosened the google.com one a bit.
- UI widgets are not re-created if it can be avoided, which should help responsiveness a bit on slower machines.
- EDIT: I made a SVG-based icon on what I thought was another branch, but apparently it got into master. Oops. That can be reverted later. >_>

Hopefully this is a little better than last time. Some testing may be needed, there are probably some UI interactions which can still cause errors.
Also, install this fresh, it won't work as an update since the list format has changed significantly.

### CODE REVIEW

**Comment by Nateowami** [comment]
This is pretty good! I can't seem to get the apply button to work though (nothing happens; no errors in console). I also noticed you can't (directly) change the position of a locked list. It also seems a little odd to click "apply" to create a list (generally apply seems to mean "put the new settings into effect, but don't close this dialog yet.")

OK, here's an interesting bug: What appears to happen when you click "apply," is that the filter gets added to the default list. I just added `"dummy" -> "superdummy"` to the default list through the UI. It replaced the `*googlecode.*` filter. 

Sorry to be _super_ slow about this pull request; we're gone right now.

Edit: We could consider moving the second row of buttons on the top left to the bottom. Might make it look slightly less cluttered. Just a thought. Also, I don't expect this to be bug-free, but perhaps the list editing could get fixed. And now I should go read the code...

**Comment by JoshTheDerf** [comment]
@Nateowami Actually, I'm noticing some strange bugs too. The extension sometimes locks up for no reason and stops filtering things, while causing sites to hang waiting for it. I'll investigate.

When hitting apply (for me), the item gets added to the top of the list, no matter what, of the first-selected list I have no clue...

Changing a position of a locked list isn't that big a deal, since you'd only do that if you had already created a new list. :/

As for moving buttons, that can wait. At the moment the whole UI is terribly laid out from a design perspective.

No problem on taking awhile. Enjoy your trip! :)

**Comment by Nateowami** [comment]
I just tried a few things (kept removing and reinstalling in order to get a clean slate). The behavior is consistent for me: Whatever filter gets selected first is the one that get's updated when you click apply.

To reproduce:
1. Uninstall Backloader.
2. Install Backloader.
3. Visit options page.
4. Click on "*google.com*"
5. Create a new list, using default options.
6. Click "Add rule." An undersized (in height) filter appears.
7. Type in "joe" for the source, and "bob" for the destination.
8. Click apply (filter editor disappears, nothing else).
9. Switch back to the default list.
10. Observe that "*google.com*" has been changed to "joe".

At which step does your experience deviate? 

This is really great though; looking forward to ironing this out and releasing it. :smile:

**Comment by JoshTheDerf** [comment]
@Nateowami Ah, that makes sense. Should be a relatively easy fix. :)

Totally trying to do school work right now. x]

**Comment by JoshTheDerf** [comment]
@Nateowami Where we're staying right now, on requests to many pages, this div is injected by something malicious:

``` html
<div id="tempDIv"><div id="newDiv_link" style="position:fixed;z-index:99999;opacity:.0;filter:alpha(opacity=0);left:0px;top:0px;width:100%;height:100%;background-color:#FFF;"></div></div>
```

On clicking on that div (anywhere on the page), you get redirected to a random advertising site. (Or more often [a page indicating that there are no valid ads for your page, in Chinese](http://ji.ihualun.com/show/zl?uid=566&zid=506&1). )

The script comes from here. `kw` is whatever site you're visiting, `type` 2 is the invalid page, `type` 1 is often an ad redirect script.:

```
http://69.197.191.138:51688/keywords/?type=1&kw=
```

^ Just for the record, that IP looks really vulnerable. ISS+PHP 5.2, and an open MySQL port, among other things.

The latest commit hides the symptoms by simply setting tempDIv's display property to none.

**Comment by Nateowami** [comment]
Oh, wow! Presumably it injects a script, which injects the `div`? Is the `div` blank? And surely this doesn't happen with HTTPS? Thanks for adding this; definitely a good feature. And it wouldn't be a bad idea to add the IP address as a custom rule. Oddly enough, a reverse IP lookup points to Kansas City, Missouri.

EDIT: In as much as the multiple lists isn't working yet, I won't merge this yet. When I find time to fix it I'll merge it and fix it, then release. Or if you beat me to it that's fine.

**Comment by JoshTheDerf** [comment]
@Nateowami Multiple lists isn't working yet? I use them frequently. O-o

And yeah, I already did a nmap scan and reverse IP lookup. Tonight I'll test to see if the network downstairs is affected.

Interestingly, there seems to be no script injected, other than that, that I can tell. I think the requests are being initiated by the router. (Initiator is "Other") That doesn't explain what backCall is though.

Haven't yet tested with HTTPs. Haven't actually been using the net much here. Only noticed the issue last night.

**Comment by Nateowami** [comment]
> Interestingly, there seems to be no script injected, other than that, that I can tell. I think the requests are being initiated by the router. (Initiator is "Other") That doesn't explain what backCall is though.

So is the script injected, which in tern injects the div? And what is `backCall` about? `EDIT: Ok, I see backCall.` Or the script _isn't_ injected, but it gets loaded anyway, and it injects the div (and presumably adds an even listener)?

Regarding multiple lists, see the last comment from May 5. Haven't tried it since then, so I didn't expect anything to change.

If you have two devices there, you could try running a server on one and accessing it on the other. If anything gets injected that would be a sure sign the router is affected. Have you tried signing in with admin/admin? That's the TP-Link default; don't know about Tenda. If you have physical access it might say on the bottom (ours does).

EDIT 2: Never saw commit 424994b903744f5abca1d22b2e253583e38fd4d8. I will merge when I have a moment to look at it (pretending to do physics right now). Thanks, and great work!

**Comment by Nateowami** [comment]
Merging now. I'm aware of a bug, but this pull request (Shouldn't it be _merge_ request? That's what GitLab calls them) has gone on a long time, and I'll open another issue for that. Would have merged long ago if I'd noticed 424994b903744f5abca1d22b2e253583e38fd4d8!

Edit: Can't remember the last time I've merged a PR!

**Comment by JoshTheDerf** [comment]
@Nateowami Hehe, sorry I didn't make that commit more clear. I hadn't taken a look at this recently.

I actually have full control over the router. The password and username are prefilled. (No idea why) It's all in Chinese though.

I haven't tried GitLab. How is it? (Email material.)

Sorry it took so long to reply, just finished teaching and dinner here. Exhausted.

**Comment by Nateowami** [comment]
@Tribex Haven't tried GitLab either (their logo is so ugly). But I think it will be home for my web-based projects of the future (you know, those grand "when I finish XYZ, I'll make... [grand idea]"). Actually, writing this has gotten me thinking of putting our family sites there. We'll see. Again, thanks for the great work!

**Comment by JoshTheDerf** [comment]
@Nateowami For private projects, couldn't you just use... git? (Maybe a VPS too?)
Anyway, this can be closed, getting offtopic.

**Comment by Nateowami** [comment]
Yeah, and that's what I do. But it's nice to be able to track issues, and view nice diffs, etc. And yeah, this is already closed. <sup>But that doesn't keep us from talking! :smile:</sup>

**Comment by JoshTheDerf** [comment]
Oh, you're right, it is. :fearful:

**Pull request merged**
